Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/05/2021
Var
// Seção de Declarações das variáveis 
cels:real
faren:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("Digite o valor do faren")
Para faren <-50 ate 65 faça
cels<-5/9*(faren-32)
escreva(cels)
fimpara
Fimalgoritmo